name: Create a release on pypi.org

on:
  push:
  pull_request:

jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: "Install dependencies"
        run: |
          pip install --upgrade setuptools pip
          pip install --upgrade -r dev-requirements.txt
          pip freeze

      - name: "Build distribution archives"
        run: |
          python setup.py sdist bdist_wheel

      # This step is only run when a new tag is pushed
      # all previous steps always run in order to exercise them
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
